services:
  api:
    build: .
    container_name: game-api
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    command: >
      sh -c "sleep 10 && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    restart: always

  db:
    image: mysql:8
    container_name: game-db
    restart: always
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  #alembic:
  #  build: .
  #  depends_on:
  #    - db
  #  env_file: .env
  #  command: alembic upgrade head
  #  volumes:
  #    - .:/app
  #  entrypoint: ["sh", "-c", "alembic upgrade head"]

  alembic-dev:
    build: .
    depends_on:
      - db
    env_file: .env
    volumes:
      - .:/app
    command: tail -f /dev/null


  tests:
    build: .
    container_name: game-tests
    depends_on:
      - api
    env_file:
      - .env
    volumes:
      - .:/app
    command: >
      sh -c "sleep 15 && pytest --cov=app --cov-report=term --cov-report=html --cov-fail-under=85 tests"
    

volumes:
  mysql_data:

