"""add unique constraint for item name

Revision ID: 75de955f0f91
Revises: 8b582406d322
Create Date: 2025-04-20 05:36:33.239315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75de955f0f91'
down_revision: Union[str, None] = '8b582406d322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_item_unique_combo', 'items', ['name', 'slot', 'power'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_item_unique_combo', 'items', type_='unique')
    # ### end Alembic commands ###
