"""Remove unique constraint from item name

Revision ID: 8b582406d322
Revises: f2bcbc87053d
Create Date: 2025-04-20 05:28:12.652678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b582406d322'
down_revision: Union[str, None] = 'f2bcbc87053d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_item_name_slot_power', table_name='items')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_item_name_slot_power', 'items', ['name', 'slot', 'power'], unique=True)
    # ### end Alembic commands ###
