"""changed ability to abilities

Revision ID: 9109a5f1f7af
Revises: 9556edc443cc
Create Date: 2025-04-20 16:36:13.498447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9109a5f1f7af'
down_revision: Union[str, None] = '9556edc443cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('abilities', sa.JSON(), nullable=False))
    op.drop_column('characters', 'ability')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('ability', mysql.JSON(), nullable=False))
    op.drop_column('characters', 'abilities')
    # ### end Alembic commands ###
