"""changes abilities to ability

Revision ID: 9556edc443cc
Revises: 96a1e300c7a9
Create Date: 2025-04-20 16:33:40.914744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9556edc443cc'
down_revision: Union[str, None] = '96a1e300c7a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('ability', sa.JSON(), nullable=False))
    op.drop_column('characters', 'abilities')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('abilities', mysql.JSON(), nullable=False))
    op.drop_column('characters', 'ability')
    # ### end Alembic commands ###
