"""changing back to non-unique items

Revision ID: 96a1e300c7a9
Revises: 75de955f0f91
Create Date: 2025-04-20 06:47:38.965925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96a1e300c7a9'
down_revision: Union[str, None] = '75de955f0f91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_item_unique_combo', table_name='items')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_item_unique_combo', 'items', ['name', 'slot', 'power'], unique=True)
    # ### end Alembic commands ###
