"""Added abilities to characters

Revision ID: 9e95772da83d
Revises: 
Create Date: 2025-04-19 20:03:02.342041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9e95772da83d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_loadouts_id', table_name='loadouts')
    op.drop_table('loadouts')
    op.drop_index('ix_characters_id', table_name='characters')
    op.drop_table('characters')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('level', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('class_type', mysql.ENUM('warrior', 'mage', 'rogue', 'healer', 'ranger', 'archer'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_characters_id', 'characters', ['id'], unique=False)
    op.create_table('loadouts',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('character_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('slot', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('power', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name='loadouts_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_loadouts_id', 'loadouts', ['id'], unique=False)
    # ### end Alembic commands ###
